# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos7"
    config.vm.box_url = "https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.1/vagrant-centos-7.1.box"

  config.vm.define "ap01" do |ap01|
    ap01.vm.box = "centos7"
    ap01.vm.network "private_network", ip: "192.168.56.101"
  end

  config.vm.define "ap02" do |ap02|
    ap02.vm.box = "centos7"
    ap02.vm.network "private_network", ip: "192.168.56.102"
  end

  config.vm.define "lb" do |lb|
    lb.vm.box = "centos7"
    lb.vm.network "private_network", ip: "192.168.56.110"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

end
